# 📌 예외 처리
### 자바 메서드에서는 문제가 생기면 예외를 사용하여 자신을 호출한 메서드에 그 사실을 알려 준다.
- **예외 처리(exception handling)** : 실행 중에 생길 수 있는 '예외적인 상황'을 처리할 수 있는 깔끔하고도 부담이 없는 방법. 이 방법을 사용하면 오류 처리 코드를 한 군데로 모아둘 수 있기 때문에 코드를 이해하기도 매우 편리함

  메서드 선언에서 **`throws`** 구문을 찾으면 예외를 발생시킬 수 있다는 것을 알 수 있음

**실행 중에 오류가 발생할 수 있는 위험한 메서드의 경우에는 메서드 선언부에서 `throws SomeKindOfException` 같은 구문을 사용하여 예외를 선언해야 함.**

- **throws** : 예외를 발생시키는 것을 예외로 '던진다(throw)'라고 표현하기 때문에 `throws`라는 키워드를 사용함

### 컴파일러는 프로그래머가 위험한 메서드를 호출하고 있다는 것을 알아야 함.
```java
import javax.sound.midi.*;

public class MusicTest1 {
  public void play() {
    try {   // 위험한 부분은 try 블록에 넣는다. 여기에서 예외를 던질 수 있는건 getSequencer 메서드
      Sequencer sequencer = MidiSystem.getSequencer();
      System.out.println("Successfully got a sequencer");
    } catch (MidiUnavailableException e) {  // 예외적인 상황이 일어났을 때 할 일을 지정하기 위한 catch 블록을 만든다.
      System.out.println("Bummer");         // getSequencer()를 호출했을 때 MidiUnavailableException이 발생할 수 있다는 것을 의미
    }
  }

  public static void main(String[] args) {
    MusicTest1 mt = new MusicTest1();
    mt.play();
  }
}
```

### 예외도 객체이다.
예외는 `Exception`이라는 타입의 객체이다. `Exception` 타입의 객체에는 `Exception` 하위 클래스의 모든 인스턴스가 포함됨
```java
try {
  // 위험한 일을 한다.
} catch (Exception e) {
  // 문제를 처리한다.
}
```
위 코드의 **`catch`** 인자는 `Exception` 타입으로 선언되어 있고 매개변수는 `e`라는 이름을 가진 레퍼런스 변수이다.

- 예외를 던지는 위험한 코드
  ```java
  public void takeRisk() throws BadException { // BadExceptoin을 던질 수 있다는 것을 외부에 알림
    if (abandonAllHope) {
      throw new BadException();                // 새로운 Exception 객체를 만들고 던짐
    }
  }
  ```

- 그 위험한 메서드를 호출하는 코드
  ```java
  public void crossFingers() {
    try {
      anObject.takeRisk();
    } catch (BadException e) {
      System.out.println("Aaargh!");
      e.printStackTrace(); // 예외 상황을 해결할 수 없다면 printStackTrace() 메서드를 써서 스택 트레이스(stack trace) 정도는 해 줘야 함
    }
  }
  ```
  한 메서드에서 던진 것을 다른 메서드에서 잡아야 한다. 예외는 언제나 그 메서드를 호출한 곳으로 던져진다. 예외를 던지는 메서드에서는 반드시 그 메서드에서 예외를 던질 수 있다는 것을 선언해야 함


### try/catch 블록에서의 흐름 제어
- try 블록이 **성공**하면 (`doRiskyThing()`에서 예외를 던지지 않으면)
  ```java
  try {
    Foo f = x.doRiskyThing();
    int b = f.getNum();
  } catch (Exception e) { 
    System.out.println("failed"); // catch 블록에 들어 있는 코드는 실행되지 않음
  }

  System.out.println("We made it!");
  
  // 출력 결과:
  // We made it!
  ```

- try 블록이 **실패**하면 (`doRiskyThing()`에서 예외를 던지면)
  ```java
  try {
    Foo f = x.doRiskyThing();
    int b = f.getNum();     // try 블록의 나머지 부분은 절대 실행되지 않음
  } catch (Exception e) {
    System.out.println("failed");
  }

  System.out.println("We made it!);
  // 출력 결과:
  // failed
  // We made it!
  ```


- **무조건 실행할 내용**을 지정하는 방법 (예외 발생 여부와 상관없이 무조건 실행할 코드는 **`finally`** 블록에 집어넣으면 됨)
  ```java
  try {
    turnOvenOn();
    x.bake();
  } catch (BakingException e) {
    e.printStackTrace();
  } finally {
    turnOvenOff();
  }
  ```
  - `try` 블록이 **실패**하면, 바로 `catch` 블록으로 넘어감. `catch` 블록이 종료되면 `finally` 블록이 실행. `finally` 블록이 종료되면 나머지 부분 실행
  - `try` 블록이 **성공**하면, `catch` 블록은 건너뛰고 `finally` 블록으로 넘어감. `finally` 블록이 종료되면 그 메서드의 나머지 부분이 실행
  - `try` 또는 `catch` 블록에 `return` 명령문이 있어도 `finally` 블록은 실행됨


### 메서드에서 예외를 두 개 이상 던질 수도 있다.
- 예외를 여러 개 잡는 방법
  ```java
  public class Laundry {
    public void doLaundry() throws PantsException, LingerieException {  // 예외 두 개 선언
      // 두 가지 예외를 던질 수 있는 코드
    }
  }
  ```
  ```java
  public class WashingMachine {
    public void go() {
      Laundry laundry = new Laundry();
      try {
        laundry.doLaundry();
      } catch (PantsException pex) {    
        // 복구 코드
  
      } catch (LingerieException lex) {
        // 복구 코드

      }
    }
  }
  ```

### 예외와 다형성
다른 모든 객체와 마찬가지로 `Exception`도 다형적으로 참조할 수 있다.
예외의 장점 가운데 하나는 메서드에서 그 메서드에서 던질 가능성이 있는 모든 예외를 명시적으로 선언하지 않아도 된다는 점이다.
`catch` 블록도 마찬가지로, 던져지는 모든 예외를 처리할 수만 있다면 모든 예외 객체의 타입별로 `catch` 블록을 따로 만들 필요는 없다

- ① 던지고자 하는 예외의 상위 클래스 타입을 이용하여 예외를 선언할 수 있다.
  ```java
  public void doLaundry() throws ClothingException {
  }
  ```
  `ClothingException`으로 선언하면 `ClothingException`의 모든 하위 클래스를 던질 수 있다.

  **즉, `doLaundry()`에서 각각 따로 선언하지 않고도 `PantsException`, `LingerieException`, `TeeshirtException`, `DressShirtException` 등을 던질 수 있다.**

- ② 던져지는 예외의 상위 클래스 타입을 써서 예외를 잡을 수 있다.
  ```java
  try {
    laundry.doLaundry();
  } catch (ClothingException cex) {
    // 복구 코드
  }
  ```
  `ClothingException`의 하위 클래스를 모두 잡을 수 있다
  ```java
  try {
    laundry.doLaundry();
  } catch (ShirtException shex) {
    // 복구 코드
  }
  ```
  `TeeShirtException`과 `DressShirtException`만 잡을 수 있다.

#### 따로 처리해야 하는 예외에 대해서는 별도의 `catch` 블록을 만들자
```java
try {
  laundry.doLaundry();
} catch (TeeShirtException tex) {
  // TeeShirtException 처리
} catch (LingerieException lex) {
  // LingerieException 처리
} catch (ClothingException cex) {     // 다른 ClothingException은 모두 여기에서 잡아냄
  // 기타 모든 ClothingException 처리
}
```
- 코드에서 `TeeShirtException`과 `LingerieException`을 다른 방법으로 처리한다면 각각에 대해 **서로 다른 `catch` 블록**을 만들면 됨
- 모두 똑같은 식으로 처리한다면 나머지를 처리하기 위한 `ClothingException`을 추가하면 됨

#### catch 블록을 여러 개 사용할 때는 작은 것부터 큰 것으로 나열해야 한다.
- 상속 트리에서 위로 올라갈수록 `catch` '바구니'가 커진다.
- 상속 트리에서 밑으로 내려올수록, 즉 더 구체적인 `Exception` 클래스일수록 `catch` 바구니는 작아진다.
- 모든 `catch` 인자의 어머니는 Exception 타입이다. 런타임 예외를 포함한 모든 예외를 잡아낼 수 있다. 따라서 테스트 과정을 제외하면 Exception에 대한 catch 블록을 만드는 일은 거의 없다.

### 예외를 처리하고 싶지 않으면 선언을 통해서 그냥 피해 버려도 된다.
```java
public void foo() throws ReallyBadException {
  // try/catch 없이 위험한 메서드 호출
  laundry.doLaundry();
}
```

### 예외와 관련된 규칙
- ① `try`없이 `catch`나 `finally`만 사용할 수는 없다.
  ```java
  void go() {
    Foo f = new Foo();
    f.foof();
    catch(FooException ex) { }
  }
  ```
  `try` 블록이 없음..
  
- ② `try`와 `catch` 사이에 코드를 집어넣을 수 없다.
  ```java
  try {
    x.doStuff();
  }
  int y = 43;
  } catch (Exception ex) { }
  ```
  `try`와 `catch` 사이에는 코드를 집어넣을 수 없음..
  
- ③ `try` 뒤에는 반드시 `catch`나 `finally`가 있어야 한다.
  ```java
  try {
    x.doStuff();
  } finally {
    // 뒷정리
  }
  ```
  `catch` 블록이 있어도 `finally`가 있으면 문법적으로 문제가 없음. 하지만 `try`만 달랑 있는 건 안됨..
  
- ④ `try` 뒤에 (`catch` 없이) `finally`만 있으면 예외를 선언해야 한다.
  ```java
  void go() throws FooException {
    try {
      x.doStuff();
    } finally { }
  }
  ```
  `try`만 있고 `catch`가 없으면 처리하거나 선언하거나 규칙을 만족시키지 못함.. 반드시 예외 선언 해야됨..
